services:

  asking-frontend:
    container_name: asking-frontend
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    depends_on:
      - asking-api
    restart: unless-stopped
    ports:
      - 127.0.0.1:3580:80
    environment:
      - REACT_APP_API_URI=https://asking.pussthecat.org

  asking-api:
    container_name: asking-api
    build: ./api
    depends_on:
      - asking-database
    restart: unless-stopped
    ports:
      - 127.0.0.1:3581:3001
    environment:
      - DATABASE_URI=postgres://asking:changeme@asking-database:5432/asking

  asking-database:
    container_name: asking-database
    image: postgres:14
    environment:
      - POSTGRES_PASSWORD=changeme
      - POSTGRES_USER=asking
      - POSTGRES_DB=asking
    volumes:
      - postgresdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U asking']
      interval: 10s
      timeout: 5s
      retries: 5
