version: '3'

services:
  asking-database:
    image: postgres
#    ports:
#      - 127.0.0.1:5432:5432
    environment:
      - POSTGRES_PASSWORD=changeme
      - POSTGRES_USER=asking
      - POSTGRES_DB=asking
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U asking']
      interval: 10s
      timeout: 5s
      retries: 5

  asking-api:
    build: ./api
    links:
      - asking-database
    depends_on:
      - asking-database
    restart: unless-stopped
#    expose:
#      - 8080
    ports:
      - 127.0.0.1:3581:3001
    environment:
      - DATABASE_URI=postgres://asking:changeme@asking-database:5432/asking

  asking-frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    depends_on:
      - asking-api
    restart: unless-stopped
#    expose:
#      - 80
    ports:
      - 127.0.0.1:3580:80
    environment:
      - REACT_APP_API_URI=https://asking.pussthecat.org
